### ISSUE TITLE
Stockable Custom field issue

### ISSUE THREAD

**Issue by goudmahendra** [breakdesigns/stockablecustomfields#13] opened 2017-12-01 11:51 UTC
I am using stockable custom field plugin for my virtuemart project. I am accessing virtuemart using virtuemart  Frontend-Administration for non-Backend Users. when I click new variation button on chrome browser. I have got the following error.

Failed to load resource: the server responded with a status of 403 (Forbidden)

 http://update.spotlightforyou.com/administrator/index.php?option=com_virtuemart&view=product&task=getData&format=json&virtuemart_product_id=235&type=fields&id=78&row=3 403 (Forbidden)
 
works on firefox.

Please help

Thanks

**Comment by sakiss** [comment] 2017-12-01 11:54
Not sure that this has to do with the plugin.
The 403 is server response when you try to access "non-allowed" resources based on permissions or set accessibility.
Please check your user's permissions when trying that.
Also what happens with other types of custom fields?

**Comment by goudmahendra** [comment] 2017-12-01 11:57
well only issue in new variation button. rest are working fine. when I am choosing from custom field drop down it add new variation. if its permission issue same should happen on firefox but its working fine there.

**Comment by sakiss** [comment] 2018-07-27 10:40
Closed as cannot reproduced

**Closed by sakiss** 2018-07-27 10:40 UTC
